site_name: searge | Cyberdeck
site_url: "https://searge.pp.ua/deck"
theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    - scheme: nord-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: nord-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - header.autohide
    - navigation.indexes
    - search.suggest
    - search.share
docs_dir: core
hooks:
  - hooks/folder_to_index.py
plugins:
  - obsidian-bridge
  - search
  - privacy
markdown_extensions:
  - obsidian_callouts
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
